kind: Pod
apiVersion: v1
metadata:
  name: app
  labels:
    app: demo.85
  namespace: default
spec:
  containers:
  - image: zookeeper
    imagePullPolicy: IfNotPresent
    name: zookeeper
  - image: kafka
    imagePullPolicy: IfNotPresent
    name: kafka
  - image: spark
    imagePullPolicy: IfNotPresent
    name: spark
  - image: mongodb
    imagePullPolicy: IfNotPresent
    name: mongodb
  - image: servidor_flask
    imagePullPolicy: IfNotPresent
    name: servidorflask
    ports:
    - containerPort: 5000
